# Generated by Django 2.2.7 on 2019-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product Name', models.CharField(max_length=200)),
                ('Producent Name', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('count', models.PositiveSmallIntegerField(verbose_name='In Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service Name', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
