# Generated by Django 2.2.7 on 2019-11-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0002_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
