# Generated by Django 2.2.7 on 2019-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0003_auto_20191126_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='question_text',
            field=models.CharField(default='xxx', max_length=200),
        ),
    ]
