# Generated by Django 2.2.7 on 2019-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0004_product_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product Name',
            field=models.CharField(default='gowno', max_length=200),
        ),
    ]
