# Generated by Django 2.2.7 on 2019-11-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0006_auto_20191126_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product Name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='question_text',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
