# Generated by Django 2.2.7 on 2020-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectBase', '0009_auto_20200102_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
