# Generated by Django 2.2.7 on 2020-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0010_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('producent_name', models.CharField(max_length=200, verbose_name='Producent Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('count', models.PositiveSmallIntegerField(verbose_name='In Stock')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Picture')),
            ],
        ),
    ]
