# Generated by Django 2.2.7 on 2020-01-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0012_auto_20200102_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_pictures/', verbose_name='Picture'),
        ),
    ]
