# Generated by Django 2.2.7 on 2020-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0013_auto_20200104_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Picture'),
        ),
    ]
