# Generated by Django 2.2.7 on 2020-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0018_auto_20200105_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='logo.jpg',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Picture'),
        ),
    ]
