# Generated by Django 2.2.7 on 2020-01-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0019_auto_20200105_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='image',
            new_name='logo.jpg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='logo.jpg',
            new_name='image',
        ),
    ]
