# Generated by Django 2.2.7 on 2020-01-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0021_auto_20200105_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
