# Generated by Django 2.2.7 on 2020-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0023_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200, verbose_name='Title')),
                ('details', models.CharField(default='0000000', max_length=1000, verbose_name='News details')),
            ],
        ),
    ]
