# Generated by Django 2.2.7 on 2020-01-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0024_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
