# Generated by Django 2.2.7 on 2020-01-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0026_new_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='new',
            name='date',
        ),
        migrations.AddField(
            model_name='new',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
