# Generated by Django 2.2.7 on 2020-01-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0027_auto_20200107_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='new',
            name='updated_on',
        ),
    ]
