# Generated by Django 2.2.7 on 2020-01-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0028_auto_20200107_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
    ]
