# Generated by Django 2.2.7 on 2020-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0029_auto_20200110_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=1000, verbose_name='Product Description'),
        ),
    ]
