# Generated by Django 2.2.7 on 2020-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBase', '0030_auto_20200111_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(default='', max_length=1000, verbose_name='Product Description'),
        ),
    ]
